# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:           "/:title"
relative_permalinks: true

# Setup
title:               Think Like an Idiot
tagline:             "Programming Made Dead Simple"
description:         "Programming and making websites for the average citizen."
url:                 http://thinklikeanidiot.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Adrian Li
  url:               https://twitter.com/adrianmcli
  email:             li.adrianmc@gmail.com

# Custom vars
version:             1.0.0

# Custom plugins
gems:
  - jekyll-sitemap