# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Think Like an Idiot
tagline:             ""
description:         "An experiment in bettering computer and programming literacy."
url:                 http://thinklikeanidiot.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Adrian Li
  url:               https://twitter.com/adrianmcli
  email:             li.adrianmc@gmail.com

# Custom vars
version:             1.0.0

# Custom plugins
gems:
  - jekyll-sitemap